/* global sharing */
var nouns = [],
    verbs = [];
var sentences = [
  ' She really looked almost wild.',
  ' But it is always so.',
  ' You alluded to something else.',
  ' He seldom appeared really animated.',
  ' They were natural and just.',
  ' But so they always are.',
  ' It is really too distressing.',
  ' They were, therefore, to go.',
  ' You do not look well.',
  ' He knows where we live.',
  '  He readily agreed to it.',
  ' He placed himself by her.',
  ' It is too long ago.',
  ' It was very little less.',
  ' He has more to give.',
  ' The King Went for Him.',
  ' Â But that\'s what they do.',
  ' Â It was very curious, somehow.',
  ' Â It was cool in there.',
  ' Â So on we prowled again.',
  '  We talked it all over.',
  ' Â You got to stay always.',
  ' Â It was so long ago.',
  '  It was just dark now.',
  ' Â That\'s what it starts with.',
  ' Â You do it pretty awkward.',
  ' Â You must a missed him.',
  '\'  Down, down, down.',
  '\' said the King sharply.',
  '  We were not regularly allowanced.',
  ' He was cruel, but cowardly.',
  ' He did nothing of himself.',
  ' There was no deceiving him.',
  ' And yet you have seen.',
  ' Do not join in it.',
  ' It is most refreshingly unusual.',
  ' He had even smoked there.',
  '  It seems that it was.',
  ' Let\'s have it straight, now.',
  ' We will talk about that.',
  ' It must have bled considerably.',
  ' He has seen too much.',
  ' They have now fled together.',
  ' It has been considered artistic.',
  ' They were evidently all deserted.',
  ' So much is fairly clear.',
  '  They must have noticed it.',
  '  No-one drank very much either.',
  '  But as it is ...',
  '  He also felt relatively comfortable.',
  '  That\'s all been sorted out.',
  '  But that could not be.',
  '  She followed, and they disappeared.',
  '  This being you must create.',
  ' But this is false reasoning.',
  ' Well, go \'long with you.',
  ' It was not dark, yet.',
  ' He\'s a going up there.',
  ' He was gloomy and desperate.',
  ' Now you think it over.',
  ' But it\'s so dim, now.',
  ' He could not help it.',
  ' He was humiliated and angry.',
  ' He was looking tolerably mellow.',
  ' But let\'s swear again, anyway.',
  ' They studiously avoided each other.',
  ' It\'s your turn to watch.',
  ' They did not talk much.',
  ' We can find out quick.',
  ' His thought was, to fly.',
  ' you go for her looks.',
  ' She could not understand it.',
  ' All as they should be.',
  ' They are all indescribable alike.',
  ' Something else to think of.',
  ' He had not dreamed them.',
  ' He advanced towards it trembling.',
  ' Philologically considered, it is absurd.',
  ' Perchance ye need it not.',
  ' There comes the other watch.',
  '  But this is not all.',
  ' They were hidden down there.',
  ' this may grow too serious.',
  ' There, now ye may go.',
  ' But no more of this.',
  '  Nor was this long wanting.',
  ' But it is not so.',
  ' Stowing Down and Clearing Up.',
  ' But this is not all.',
  '  You are hardly serious enough.',
  '  That is not very pleasant.',
  '  It\'s delightful to watch them.',
  '  They are quite, quite, blue.',
  '  That gets rid of him.',
  '  But it seems very unfair.',
  '  It is somewhat too sensational.',
  '  He seemed very much disappointed.',
  '  He knows perfectly well why.',
  '  Well, Cecily is a darling.',
  '  It would be most unfriendly.',
  '  It\'s a very painful parting.',
  '  [Crossing to her, and kneeling.',
  '  He grows more interesting hourly.',
  '  [Rising and going to her.',
  '  You have been christened already.',
  '  That is the important thing.',
  '  That\'s very forward of them.',
  ' Much depends on your reply.',
  '  It looks so calculating .',
  '  [Rising and drawing herself up.',
  ' Let her be sent for.',
  ' Give up the moody brooding.',
  ' He says it\'s very clever.',
  '  He drank at her bidding.',
  ' Give him the key too.',
  ' He will ask for it.',
  ' he cried continually without listening.',
  ' And it can be cured.',
  ' Tap with it: they do.',
  ' He coasted them, walking warily.',
  ' All or not at all.',
  ' She might like something tasty.',
  ' Must get those settled really.',
  ' He stooped and gathered them.',
  '  He felt here and there.',
  ' Get rid of him quickly.',
  ' Handsome is and handsome does.',
  ' Feels locked out of it.',
  ' No, he\'s going on straight.',
  ' Thank you: not having any.',
  ' Still like you better untidy.',
  ' Grows all the same after.',
  ' Strange feeling it would be.',
  ' As broad as it\'s long.',
  ' It\'s well out of it.',
  ' Shaking sleep out of it.',
  ' Learn anything if taken young.',
  ' Tantalising for the poor dead.',
  ' Turning green and pink decomposing.',
  ' His sleep is not natural.',
  ' We learned that from them.',
  ' More Irish than the Irish.',
  ' Just to see: before: dressing.',
  ' To be seen and heard.',
  ' Want to fix it up.',
  ' Everything was going swimmingly ...',
  ' He died in his sleep.',
  ' We were weak, therefore worthless.',
  ' Lobbing about waiting for him.',
  ' It\'s after they feel it.',
  ' Think no more about that.',
  ' He got it this morning.',
  ' Supposed to be well connected.',
  ' They are not even registered.',
  ' Squarepushing up against a backdoor.',
  ' She\'s taking it all in.',
  ' Wanted to try that often.',
  '  Never know anything about it.',
  ' If it was it was.',
  ' Molly looks out of plumb.',
  ' Bolting to get it over.',
  ' You may have heard perhaps.',
  ' The belly is the smoothest.',
  ' Now your best French polish.',
  '  O, yes, mention there is.',
  '      It has vanished long ago...',
  ' They mock to try you.',
  ' He is all in all.',
  ' The incumbent they called him.',
  ' Surely, there ought to be.',
  ' Drop in whenever you like.',
  ' what do you call him...',
  '  He handed her a shilling.',
  ' Well now, look at that.',
  '  All turned where they stood.',
  ' The real classical, you know.',
  '  He drank and strayed away.',
  '  That is to say she.',
  ' Not make him walk twice.',
  ' How warm this black is.',
  ' O, not in the least.',
  '  He knows it well too.',
  ' Still always nice to hear.',
  ' Yes, yes, will tell you.',
  ' He waits while you wait.',
  ' He waits while you wait.',
  ' Deaf wait while they wait.',
  ' For him then not for.',
  ' See her from here though.',
  ' Look at this, says he.',
  ' We let them come in.',
  ' Sometimes Molly and Milly together.',
  ' Because they want it themselves.',
  ' That\'s the secret of it.',
  ' Or even hear of it.',
  ' Come in, all is prepared.',
  ' Instead of talking about nothing.',
  ' This wet is very unpleasant.',
  ' Tell you what it is.',
  ' Healthy perhaps absorb all the.',
  ' Not going to hurt you.',
  ' They floated, fell: they faded.',
  ' Never know what you find.',
  ' It never comes the same.',
  ' Go thou and do likewise.',
  ' She is more taking then.',
  ' Breathe it deep into thee.',
  ' See her in her dishybilly.',
  ' Caraway seed to carry away.',
  ' Just you try it on.',
  ' All that\'s left of him.',
  ' Fresh thing was never touched.',
  ' Tell us, there\'s a dear.',
  ' But you must never tell.',
  ' He wants to go straight.',
  ' You are a necessary evil.',
  ' Stop that and begin worse.',
  ' It is because it is.',
  ' It runs in our family.',
  ' Move on out of that.',
  ' Best thing could happen him.',
  ' Pretty thick that was certainly.',
  ' Quite dark, regular brunette, black.',
  ' You had to come back.',
  ' As more than inevitable, irreparable.',
  ' we can borrow until then.',
  ' Yes, it is really wonderful.',
  ' Ask her to come in.',
  ' So you are quite alone.',
  ' Then it really was he.',
  ' Still, with us you might.',
  ' Yes, and you did so.',
  ' That is nice of you.',
  ' It is nice of you.',
  ' Do talk of something cheerful.',
  ' No, indeed, you shall not.',
  ' No, not just at present.',
  ' Do not do anything foolish.',
  ' Then you will be free.',
  ' But help may be near.',
  ' it\'s all dark in here.',
  ' Yes, it\'s far more becoming.',
  ' No, not in the least.',
  ' Thank you for that wish.',
  ' They were on the top.',
  ' Never to see him again.',
  ' No, that is all over.',
  ' No, that is just it.',
  ' No, that is just it.',
  ' Yes, absolutely clear and certain.',
  ' Now it is all over.',
  ' You must not do that.',
  '  He knows nothing about it.',
  '  But you never sat better.',
  '  You will like them always.',
  '  You have lived since then.',
  '  It is their distinguishing characteristic.',
  '  They would love his playing.',
  '  He was brilliant, fantastic, irresponsible.',
  '  It is far too fragile.',
  '  That is all over now.',
  '  This is merely the beginning.',
  '  He was pleased by it.',
  '  He had made him premature.',
  '  He means you no good.',
  ' you should never forget it.',
  '  He was puzzled and anxious.',
  '  That could not be denied.',
  '  You are shallow and stupid.',
  '  The thing was horribly apparent.',
  '  They would be happy together.',
  '  It was selfish of her.',
  '  Ultimately, however, it did die.',
  '  What is done is done.',
  '  What is past is past.',
  '  Something has changed you completely.',
  '  That is charming of you.',
  '  It was pretty of her.',
  '  He was trembling all over.',
  '  It would have been impossible.',
  '  It would be always alive.',
  '  Here:  this will do.',
  ' Nothing seems to us changed.',
  '  He had not painted it.',
  '  At least nothing should be.',
  '  You have not been fine.',
  '  And there is worse behind.',
  '  He had never done that.',
  '  You worshipped yourself too much.',
  '  He knew what it was.',
  '  No:  everything was still.',
  '  A sudden thought struck him.',
  '  You were stern, harsh, offensive.',
  '  You know what they are.',
  ' The thing is quite simple.',
  '  Try and make him come.',
  '  He was prisoned in thought.',
  '  You should have killed him.',
  '  You should give her warning.',
  '  You must have overtired yourself.',
  '  He saw it all again.',
  '  He is going to faint.',
  '  He clutched at it madly.',
  '  It had lost an ideal.',
  '  You must have some secret.',
  '  There is nothing like it.',
  '  It has not marred you.',
  '  You are still the same.',
  '  You are quite flawless now.',
  '  He was perfectly safe there.',
  '  It was nothing to him.',
  '  He would go and look.',
  '  There had been something more.',
  ' There had been nothing more.',
  '  It was bright, and glistened.',
  ' There, it is all out.',
  ' He surely would have written.',
  ' We had a lovely walk.',
  ' They are just the same.',
  ' She seems better, poor dear.',
  ' Come now and be silent.',
  ' He must not stay here.',
  ' And then we may begin.',
  ' It beats, though but feebly.',
  ' You are looking pale yourself.',
  ' Forget it for the present.',
  ' Without such it is monstrous.',
  ' He believes it all himself.',
  ' You shall yet be convinced.',
  ' You had better be assured.',
  ' They are hard at it.',
  ' We all instinctively drew back.',
  ' He made no reply whatever.',
  ' We were afraid to think.',
  ' But neither must go alone.',
  ' We may never meet again.',
  ' We may be too late.',
  '  Closer and closer they drew.',
  ' for themselves and for you.',
  '   Then have thy bent unleash\'d.',
  '   Garrulous to the very last.',
  '  Speak no more of it.',
  '  Now you may go then.',
  '  It is always like this.',
  '  Like this, it was good.',
  ' On this at last conclude.',
  ' Go then with this forewarning.',
  ' Here please thee stay awhile.',
  ' He seemed delighted with it.',
  ' it was so frightfully painful.',
  ' We hoped to meet again.',
  ' She did so at once.',
  ' No sooner said that done.',
  ' by all that is holy.',
  ' You are too young yet.',
  ' She tried to grasp it.',
  ' We handled and pressed it.',
  '  She grew up admirably developed.',
  ' how divine you must look.',
  ', that may be met.',
  ' She seemed uncanny and fateful.',
  ' Hoped it was not true.',
  ' He was a chattering idiot.',
  ' It was very quiet there.',
  ' It was an extraordinary find.',
  ' Yes, it looked like cipher.',
  ' He laughed, then became serious.',
  ' He could be very terrible.',
  ' And it was true too.',
  ' He must have been shouting.',
  ' We must be cautious yet.',
  ' He struggled with himself, too.',
  ' He had something to say.',
  '  Come on, if you please.',
  '  You ought to marry her.',
  '  He would be alone, too.',
  '  But it is useless grieving.',
  ' but there was something queer...',
  ' But it\'s hard to say....',
  ' This happened morning after morning.',
  ' He was squat and ruddy.',
  ' He could see nothing there.',
  '  After that they lived apart.',
  ' There was always a certain...',
  ' He felt them within him.',
  ' He ordered the same again.',
  ' He stood still to listen.',
  ' He listened again: perfectly silent.',
  ' Not like the other tinker.',
  ' There must be some left.',
  ' but we have a few....',
  '  Our Uncrowned King is dead.',
  ' You wear them over your...',
  ' so clear and fresh, never.',
  ' It was just as well.',
  ' He might have answered rudely.',
  '  perhaps to DISCOVER the new.',
  '  But this could never be.',
  '  It will soon be gone.',
  '  She is not far off.',
  '  Nay, there\'s no comprehending it.',
  '  \'You are not going yet.',
  '  You could be free instantly.',
  '  We really must go back.',
  '  \'Why, almost bright and cheerful.',
  '  Be quick, and bring another.',
  '  He said; and all approved.',
  '  What must be, must be.',
  '  He gave a reluctant \'Yes.',
  '  There can be no other.',
  '  That we may safely affirm.',
  '  It ought not to be.',
  '  That will be quite fair.',
  '  That appears to be true.',
  '  Yes, by far the best.',
  '  There can be nothing better.',
  '  Yes, and so they will.',
  '  Nothing can be more certain.',
  '  That seems to be true.',
  '  Neither can that be denied.',
  '  By far the most like.',
  '  Then omit nothing, however slight.',
  '  That would not be creditable.',
  '  Yes, that is quite clear.',
  '  Yes, that may be expected.',
  '  That appears to be so.',
  '  No, there is nothing else.',
  '  Yes, that can hardly be.',
  ' He yawned and stretched himself.',
  ' She did not wish any.',
  ' It was musical and true.',
  ' He looked embarrassed and uneasy.',
  ' She wanted to destroy something.',
  ' If not, leave her here.',
  ' She grew accustomed to him.',
  ' Above all, there was understanding.',
  '  She went on and on.',
  ' You will make yourself ill.',
  ' She does not know it.',
  ' She had grown very old.',
  ' She was apparently very outspoken.',
  ' She carried them without wrapping.',
  ' It was all very agreeable.',
  '  She never displayed it now.',
  ' No sooner said than done.',
  ' Stand by to go about.',
  ' and now they are gone.',
  ' Listen to their gentle breathing.',
  ' They are no longer there.',
  '  Absolutely finished now, they thought.',
  ' She was very busy, stitching.',
  ' It made him quite helpless.',
  ' He could only stare, horrified.',
  '  Grandly, however, did Tootles respond.',
  ' He heard something else instead.',
  ' Darling does not blame us.',
  '  Darling would never forgive us.',
  ' There is your old bed.',
  ' That used to be Tootles.',
  '  She had to tell him.' ];
Array.prototype.pick = function() {
  return this[Math.floor(Math.random()*this.length)];
};

function generate(nounPlural, verb) {
  var generatedText = sentences.pick().trim();
  var sharedText = generatedText + ' #FiveWordsToRuinADate';
  $('#content').html(generatedText);
  var shareUrl = window.location.href.split('?')[0];
  $('#share').attr('href', shareUrl);
  $('.twitter-share-button').remove();
  $('#twitterShare').html('<a href="https://twitter.com/share" class="twitter-share-button" data-url="' + shareUrl + '" data-text="' + sharedText + '" data-lang="en">Tweet</a>');
  if (twttr.widgets) {
    twttr.widgets.load();
  }
}

function getWords(suppressGenerate) {
  $.when(
    $.ajax({
      url: 'http://api.wordnik.com/v4/words.json/randomWords?minCorpusCount=10000&minDictionaryCount=5&excludePartOfSpeech=proper-noun,proper-noun-plural,proper-noun-posessive,suffix,family-name,idiom,affix&hasDictionaryDef=true&includePartOfSpeech=noun&limit=1000&maxLength=22&api_key='+key.API_KEY,
      async: false,
      dataType:'json'
    }),
    $.ajax({
      url: 'http://api.wordnik.com/v4/words.json/randomWords?limit=1000&excludePartOfSpeech=adjective&hasDictionaryDef=true&includePartOfSpeech=verb-transitive&minCorpusCount=1000&api_key='+key.API_KEY,
      async: false,
      dataType:'json'
    })
  ).done(function(noun_data, verb_data) {
    nouns = $.map(noun_data[0], function(el) { return el.word; });
    verbs = $.map(verb_data[0], function(el) { return el.word; });
    if (!suppressGenerate) {
      generate();
    }
  });
}

$('#generate').click(function() { generate(); });
  generate();